### ISSUE TITLE
[Fabric 1.20] Map state doesn't update unless a shutdown occurs

### ISSUE THREAD

**Issue by mookman288** [granny/Pl3xMap#1] opened 2023-10-25 21:16 UTC
Hi. 

First, thank you @granny for taking over the Pl3xMap repository and providing us a space to reach out for support. Thank you to @BillyGalbreath for Pl3xMap and all of the work you've done to provide the community with such a stellar plugin. 

The issue I'm submitting today is related to the map state not updating unless a shutdown occurs. Changes to the map, the fog of war, or anything related to map state, does not update unless I perform a full shutdown. A simple reload, or save, does not allow the map to update. 

Server: Fabric 1.20
OS: Windows 8.1
Java Version: 21 LTS
Tunnel: I am using a vLan to allow access to the server and the map, so it's currently not on the Internet--but checking the map directly from the server does not update either. 

User status and location updates in real time. 

I noticed nearly identical issues with another plugin, Fastback. You can [read my issue for that plugin](https://github.com/pcal43/fastback/issues/297) if it can provide any insights. Fastback performs incremental backups of user and map data. All user data is updated regularly, but map data does not update unless I perform a full shutdown.

Based on the fact that other plugins are mirroring this issue with map state, I imagine that this is related to an issue with how plugins, like Pl3xMap, access map data. I need to eliminate Pl3xMap as the cause before I reach out to Fabric. Therefore, I am hoping someone from this community can lead me to what exactly occurs when Pl3xMap wants to read map data. 

Is this a Fabric API issue? Complication from another plugin? Is it something more intrinsic to Minecraft? Is there a setting somewhere that needs to be enabled to allow Pl3xMap access to map data in real time? Permissions issue maybe?

Here are the only relevant logs that I could find: 

```
[15:52:36] [Server thread/INFO]: [Pl3xMap] [WARN] Registering unknown vanilla block minecraft:suspicious_gravel
[15:52:36] [Server thread/INFO]: [Pl3xMap] [WARN] Registering unknown vanilla block minecraft:pitcher_crop
[15:52:36] [Server thread/INFO]: [Pl3xMap] [WARN] Registering unknown vanilla block minecraft:sniffer_egg
[15:52:36] [Server thread/INFO]: [Pl3xMap] [WARN] Registering unknown vanilla block minecraft:calibrated_sculk_sensor
[15:52:36] [Server thread/INFO]: [Pl3xMap] [WARN] Registering unknown vanilla block minecraft:pitcher_plant
[15:52:38] [Server thread/INFO]: [Pl3xMap] [INFO] Internal webserver running on 0.0.0.0:8080
[15:52:38] [Server thread/INFO]: [Pl3xMap] [INFO] Platform: fabric
[15:52:38] [Server thread/INFO]: [Pl3xMap] [INFO] Version: 1.20-443
[15:52:38] [Server thread/WARN]: Can't keep up! Is the server overloaded? Running 4208ms or 84 ticks behind
[16:52:38] [pool-13-thread-12/INFO]: Starting auto-backup
[16:52:38] [pool-13-thread-12/INFO]: Preparing local backup snapshots/<hash>/2023-10-25_16-52-38
[16:52:39] [pool-13-thread-12/INFO]: Disabling world save for 'git add'
[16:52:39] [pool-13-thread-12/INFO]: Adding 5 new or modified files to index
[16:52:39] [pool-13-thread-12/INFO]: World save re-enabled.
[16:52:39] [pool-13-thread-12/INFO]: Local backup complete.
```

Thank you for any insight you can provide!

**Comment by granny** [comment] 2023-10-28 10:17
There were a ton of builds and changes since 1.20-443. There's a good chance that your issue was fixed on builds made for a newer version of minecraft (Fixes that are available on 1.20.1 did not get backported to 1.20, for example). However, there is a chance that the current 1.20 build available on Modrinth *may* fix your issue. If it doesn't, then there's nothing else I can really do for you, unless you are able to reproduce that issue with the most recent 1.20.2 build.

**Closed by granny** 2023-10-28 10:17 UTC
Labels: invalid
